'use server';
/**
 * @fileOverview A Genkit flow for recommending entrepreneurs based on user history and preferences.
 *
 * - recommendEntrepreneurs - A function that handles the entrepreneur recommendation process.
 * - RecommendEntrepreneursInput - The input type for the recommendEntrepreneurs function.
 * - RecommendEntrepreneursOutput - The return type for the recommendEntrepreneurs function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendEntrepreneursInputSchema = z.object({
  browsingHistory: z
    .array(z.string())
    .describe('A list of entrepreneur names or categories the user has previously viewed.'),
  inferredPreferences: z
    .array(z.string())
    .describe(
      'A list of keywords or categories representing the users inferred preferences (e.g., "handmade crafts", "local food").'
    ),
});
export type RecommendEntrepreneursInput = z.infer<typeof RecommendEntrepreneursInputSchema>;

const RecommendedEntrepreneurSchema = z.object({
  entrepreneurName: z.string().describe('The name of the recommended entrepreneur.'),
  category: z.string().describe('The business category of the entrepreneur (e.g., "food", "crafts", "services").'),
  recommendationReason: z
    .string()
    .describe(
      'A brief, concise explanation (1-2 sentences) why this entrepreneur is recommended based on the user preferences.'
    ),
});

const RecommendEntrepreneursOutputSchema = z.object({
  recommendations: z.array(RecommendedEntrepreneurSchema).describe('A list of recommended entrepreneurs with reasons.'),
});
export type RecommendEntrepreneursOutput = z.infer<typeof RecommendEntrepreneursOutputSchema>;

export async function recommendEntrepreneurs(
  input: RecommendEntrepreneursInput
): Promise<RecommendEntrepreneursOutput> {
  return recommendEntrepreneursFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendEntrepreneursPrompt',
  input: {schema: RecommendEntrepreneursInputSchema},
  output: {schema: RecommendEntrepreneursOutputSchema},
  prompt: `You are an intelligent recommendation engine for "Club Patio", the loyalty app for a local marketplace called Patio Curauma.\n\nYour task is to recommend local entrepreneurs (tiendas) to a member based on their browsing history and preferences. Members earn "Sellos" (stamps) for their purchases.\n\nGenerate 3 unique recommendations. For each recommendation, provide the entrepreneur's name, their business category, and a brief, concise reason (1-2 sentences) explaining why they are a good fit for the user. Be creative with local business names.\n\nBrowsing History: {{#each browsingHistory}}- {{this}}\n{{/each}}\nInferred Preferences: {{#each inferredPreferences}}- {{this}}\n{{/each}}\n`,
});

const recommendEntrepreneursFlow = ai.defineFlow(
  {
    name: 'recommendEntrepreneursFlow',
    inputSchema: RecommendEntrepreneursInputSchema,
    outputSchema: RecommendEntrepreneursOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    if (!output) {
      throw new Error('No output generated by the recommendation prompt.');
    }
    return output;
  }
);
